"""
Verify a cryptographic signature from a file generated by generate.py.

This script reads a signed message file and verifies that the signature
is valid for the given message and SS58 address.

Usage:
    python verify.py --file message_and_signature.txt
"""

import argparse
import re
import sys
from binascii import unhexlify
from pathlib import Path

from substrateinterface import Keypair


def parse_signature_file(file_path: str) -> tuple[str, str, str]:
    """
    Parse a signature file and extract message, address, and signature.

    Supports both the old format (tab-separated) and new format (line-separated with labels).

    Args:
        file_path: Path to the file containing the signed message.

    Returns:
        Tuple of (message, address, signature_hex).

    Raises:
        ValueError: If the file format is invalid or missing required fields.
        FileNotFoundError: If the file does not exist.
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    # Try new format first (line-separated with labels)
    message_match = re.search(r"^Message:\s*(.+)$", content, re.MULTILINE)
    address_match = re.search(r"^Signed by:\s*(\S+)$", content, re.MULTILINE)
    signature_match = re.search(r"^Signature:\s*([a-fA-F0-9]+)$", content, re.MULTILINE)

    if message_match and address_match and signature_match:
        return (
            message_match.group(1).strip(),
            address_match.group(1).strip(),
            signature_match.group(1).strip(),
        )

    # Fall back to old format (tab-separated: message\n\tSigned by: ...\n\tSignature: ...)
    parts = content.split("\n\t")
    if len(parts) >= 3:
        message = parts[0]

        address_line = parts[1]
        address_prefix = "Signed by: "
        address = (
            address_line[len(address_prefix):]
            if address_line.startswith(address_prefix)
            else address_line
        )

        signature_line = parts[2]
        signature_prefix = "Signature: "
        signature = (
            signature_line[len(signature_prefix):]
            if signature_line.startswith(signature_prefix)
            else signature_line
        )

        return message.strip(), address.strip(), signature.strip()

    raise ValueError(
        "Invalid file format. Expected fields: Message, Signed by, Signature"
    )


def verify_signature(file_path: str) -> bool:
    """
    Verify a signature from a file.

    Args:
        file_path: Path to the file containing the signed message.

    Returns:
        True if signature is valid, False otherwise.
    """
    try:
        message, address, signature_hex = parse_signature_file(file_path)
    except FileNotFoundError as e:
        print(f"Error: {e}")
        return False
    except ValueError as e:
        print(f"Error: {e}")
        return False

    # Validate SS58 address format
    try:
        keypair = Keypair(ss58_address=address, ss58_format=42)
    except Exception as e:
        print(f"Error: Invalid SS58 address '{address}': {e}")
        return False

    # Convert hex signature to bytes
    try:
        signature_bytes = unhexlify(signature_hex.encode())
    except Exception as e:
        print(f"Error: Invalid signature format: {e}")
        return False

    # Verify the signature
    try:
        if keypair.verify(data=message, signature=signature_bytes):
            print(f"Signature VALID")
            print(f"  Message: {message[:80]}{'...' if len(message) > 80 else ''}")
            print(f"  Signed by: {address}")
            return True
        else:
            print(f"Signature INVALID for address: {address}")
            return False
    except Exception as e:
        print(f"Error: Verification failed: {e}")
        return False


def main():
    """Parse arguments and verify signature."""
    parser = argparse.ArgumentParser(
        description="Verify a cryptographic signature from a file generated by generate.py.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python verify.py --file message_and_signature.txt
    python verify.py --file custom_signed_message.txt
        """,
    )
    parser.add_argument(
        "--file",
        type=str,
        required=True,
        help="The file containing the message and signature to verify",
    )

    args = parser.parse_args()

    success = verify_signature(args.file)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
